version: '3.8'

services:
  matchpet-api:
    build:
      context: ./matchpet-api
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./matchpet-api/src:/app/src
      - ./matchpet-api/nodemon.json:/app/nodemon.json
    container_name: matchpet-api
    expose:
      - '8000'
    ports:
      - '8000:8000'
    command: 'npm run start-dev'
    networks:
      - internal

  matchpet-rendering-server:
    build:
      context: ./matchpet-rendering-server
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./matchpet-rendering-server/src:/app/src
      - ./matchpet-rendering-server/nodemon.json:/app/nodemon.json
    container_name: matchpet-rendering-server
    expose:
      - '8001'
    ports:
      - '8001:8001'
    command: 'npm run start-dev'
    networks:
      - internal
  
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - internal

volumes:
  mongodb_data:

networks:
  internal:
    driver: bridge
