version: '3.8'

services:
  matchpet-api:
    platform: linux/amd64
    build:
      context: ./matchpet-api
      dockerfile: Dockerfile
      target: production 
    image: "936580475072.dkr.ecr.sa-east-1.amazonaws.com/matchpet-api:latest"
    volumes:
      - ./matchpet-api/src:/app/src
      - ./matchpet-api/pm2.json:/app/pm2.json
    container_name: matchpet-api
    expose:
      - '8000'
    ports:
      - '8000:8000'
    command: 'npm run start-production'
    networks:
      - internal

  nginx:
    depends_on:
      - matchpet-api
    platform: linux/amd64
    image: "nginx:latest"
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    networks:
      - internal
  
networks:
  internal:
    driver: bridge
