name: deploy-fronted

on:
  push:
    branches: 
      - main

jobs:
  deploy-ecr:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 21.x

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_TERRAFORM_AGENT_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_TERRAFORM_AGENT_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Authenticate to the ecr service
        run: aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin 936580475072.dkr.ecr.sa-east-1.amazonaws.com 


      - name: Build docker image
        run: docker-compose -f ./backend/docker-compose-prod.yaml build
      
